<a href="https://colab.research.google.com/github/Diptesh123sannigrahi2/Diptesh123sannigrahi2.github.io/blob/main/Python_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
age = 20
print(age)

20


In [6]:
price=19.95
print(price)
type(price)

19.95


float

In [9]:
name=input("What is your name? ")
print("Hello sir "+name)

What is your name? Diptesh
Hello sir Diptesh


In [14]:
dob = input("Enter yout birth year? ")
age = 2022-int(dob)
print(age)

Enter yout birth year? 2001
21


float() --> for tranforming to float

bool() --> to bool type

str() --> to string

In [15]:
first = input("First: ")
second = input("Second: ")
print(int(first)+int(second));

First: 10
Second: 30
40


Pyhon cannot concatinate float with a str

In [21]:
course = 'Pyhon for Beginers'
print(course.upper())
print(course.find('y'))
print(course.capitalize())
print(course.encode())
print(course.replace('for','4'))

PYHON FOR BEGINERS
1
Pyhon for beginers
b'Pyhon for Beginers'
Pyhon 4 Beginers


Strings are un-mutable in python. So every method we use returns a completely new string.

In [22]:
course = 'Python for Beginers'
print('Python' in course)

True


In [23]:
print(10/3)
print(10//3)
print(10%3)

3.3333333333333335
3
1


In [24]:
print(10*3)  #normal multiplaction
print(10**3) #to the power

30
1000


In [26]:
x = 10 + 3 * 2
print(x)

16


*,/ > +,- ---> operator precidence

In [30]:
x = 3<2
print(x)

False


In [31]:
x = 3==3
print(x)

True


In [32]:
price = 25
print(price>10 and price<=30) # and operator

True


In [34]:
price = 5
print(price>10 or price<=30) # or operator

True


In [35]:
price = 5
print(not price>10) # not operator

True


In [37]:
temp = int(input('Temp of your room: '))

if temp<=20:
  print('Cold temp!')
elif temp<=30 and temp>20:
  print('Normal temp!')
elif temp>30 and temp<=40:
  print('Indian temp!')
else:
  print('Very High temp!')


Temp of your room: 40
Indian temp!


In [40]:
i = 1
while i<=5:
  print(i)
  i+=1

1
2
3
4
5


In [42]:
i = 1
while i<=5:
  print(i * '*')
  i+=1

*
**
***
****
*****


List in Python

In [72]:
names = ["John","Bob","Mosh","Sam","Mary"]
names.append("Diptesh") #add an element in the end of the list
names.pop() # remove the last element from the list
names.remove("John") # remove the specified element from the list
names.insert(0,"Atanu") # insert an element at the very specified position
n = len(names)
print(n)
print(names[0]) #first element of the list
print(names[-1]) #last element of the list
print(names[:3]) #printing the first 3 elements
print(names[-2:]) #printing last 2 elements of the list  
print(names)

5
Atanu
Mary
['Atanu', 'Bob', 'Mosh']
['Sam', 'Mary']
['Atanu', 'Bob', 'Mosh', 'Sam', 'Mary']


In [73]:
numbers = [1,3,4,5,6]
for item in numbers:
  print(item)

1
3
4
5
6


The __init__() function is called automatically every time the class is being used to create a new object.

In [3]:
class name:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def print(self):      
    print('Hello my name is '+self.name)

suv = name('Subhankar',21)
suv.print()
print(suv.age)
del suv.age #to delete age parameter from class name
del suv #to delete objects 

Hello my name is Subhankar
21


The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self, you can call it whatever you like, but it has to be the first parameter of any function in the class.

In [4]:
class Person:   
  pass  

class definitions cannot be empty, but if you for some reason have a class definition with no content, put in the pass statement to avoid getting an error.

In [5]:
class Person:
  def __init__(self,fname,lname):
    self.fname = fname
    self.lname = lname
  def printname(self):
    print(self.fname,self.lname)
x = Person("Abhisek","Kumar")
x.printname()

Abhisek Kumar


In [8]:
class Student(Person):  #Create a class named Stident, which will inherit the properties and methods from the person class
  pass

y = Student("Subhankar","Dey")
y.printname()

Subhankar Dey


Python File Open

1. "r" ---> read ---> opens a file for reading,error if the file does not exist.
2. "a" ---> append --> opens a file for appending, creates the file if it does not exist.
3. "w" ---> write ---> opens file for writing, creats the file if it does not exist
4. "x" ---> create ---> creats the specified file, returns an error if the file exists

In addition you can specify if the file should be handled as binary or text method

i. "t" ---> Text ---> Default value. Text Method

ii. "b" ---> Binary ---> Binary mode (e.g. images)

In [23]:
# write file
f = open("Test.txt","w")
f.write("Woops! I will be great")
f.close()

#open and read the file after the appending
f = open("Test.txt","r")
print(f.read())

Woops! I will be great


In [24]:
# append file
f = open("Test.txt","a")
f.write(" because i am diptesh!")
f.close()

f = open("Test.txt","r")
print(f.read())
f.close()

Woops! I will be great because i am diptesh!


In [25]:
# create file
f = open("myFile.txt","x")

In [26]:
p = open("MyFile.txt","w")
p.write("I am diptesh and i gonna be stronger!")
p.close()

n = open("MyFile.txt","r")
print(n.read())

I am diptesh and i gonna be stronger!


In [31]:
# deleting a file
import os
if os.path.exists("MyFile.txt"):
  os.remove("MyFile.txt")
else:
  print("The file does not exist!")

The file does not exist!


In [30]:
# deleting folder
import os
os.rmdir("Text")

***Why NumPy Faster than Lists ?***

NumPy arrays are stored at one continues place in memory unlike lists, so precesses can access and manipulate them very efficiently.

The behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [32]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])
print(arr[:4])

[5 6 7]
[1 2 3 4]


In [34]:
# 'step' value to determine the step of the slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:7:2])

[2 4 6]


In [38]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0, ::4]) 
print(arr[0, :4])

[1 5]
[1 2 3 4]


In [40]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,::4])

[[ 1  5]
 [ 6 10]]


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )


In [46]:
import numpy as np
arr = np.array(['a','2','3'],dtype='i')
# A non integer string like 'a' can not be converted to integer

ValueError: ignored

In [49]:
# Converting Data Type on Existing Arrays
import numpy as np
arr = np.array([1.1,2.2,3.3])
# newarr = arr.astype('i')
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64
